// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package dashboard

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/kerneels94/reports/view/layout"

func CreateReportForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-post=\"/api/dashboard/reports\" hx-target=\"#response\"><div><label for=\"incidentDate\">Incident Date:</label> <input type=\"date\" id=\"incidentDate\" name=\"incidentDate\" required></div><div><label for=\"typeOfReport\">Type of report:</label> <input type=\"text\" id=\"typeOfReport\" name=\"typeOfReport\" value=\"attempted\" required></div><div><label for=\"clientName\">Name:</label> <input type=\"text\" id=\"clientName\" name=\"clientName\" required></div><div><label for=\"clientSurname\">Surname:</label> <input type=\"text\" id=\"clientSurname\" name=\"clientSurname\" required></div><div><label for=\"clientAddress\">Address:</label> <input type=\"text\" id=\"clientAddress\" name=\"clientAddress\" required></div><div><label for=\"responderTime\">Responding time:</label> <input type=\"time\" id=\"responderTime\" name=\"responderTime\" required></div><div><label for=\"responderCallSign\">Vehicle call sign:</label> <input type=\"text\" id=\"responderCallSign\" name=\"responderCallSign\" required></div><div><label for=\"operatorName\">Operator name:</label> <input type=\"text\" id=\"operatorName\" name=\"operatorName\" required></div><div><label for=\"operatorPosition\">Operator position:</label> <input type=\"text\" id=\"operatorPosition\" name=\"operatorPosition\" required></div><div><label for=\"report\">Report:</label> <textarea cols=\"10\" rows=\"10\" name=\"report\" id=\"report\"></textarea></div><button type=\"submit\">Create Report</button></form><hr><div id=\"response\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
